version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  reviewers:
  - Armitage35
  labels:
  - dependencies
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: madge
    versions:
    - 4.0.0
    - 4.0.1
  - dependency-name: puppeteer
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: ora
    versions:
    - 5.3.0
